name: Release Build

on:
  push:
    tags:
      - 'v*'
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore src/SpecTrace/SpecTrace.csproj
      
    - name: Build Release
      run: dotnet build src/SpecTrace/SpecTrace.csproj --configuration Release --no-restore
      

    - name: Build and Publish Executable
      run: |
        # Build self-contained executable (works reliably)
        dotnet publish src/SpecTrace/SpecTrace.csproj `
          --configuration Release `
          --runtime win-x64 `
          --self-contained true `
          --output publish `
          -p:PublishSingleFile=true `
          -p:DebugType=None `
          -p:DebugSymbols=false
          
    - name: Verify Build Output
      run: |
        Write-Output "=== Build Output ==="
        Get-ChildItem -Path "publish" -Recurse
        $exe = Get-Item "publish/SpecTrace.exe"
        Write-Output "Executable size: $([math]::Round($exe.Length/1MB,2)) MB"
        
    - name: Upload Release Assets
      if: github.event_name == 'release' || startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          publish/SpecTrace.exe
        body: |
          ## 🚀 SpecTrace Release
          
          Professional Windows system information tool for comprehensive hardware analysis and diagnostics.
          
          ### 📥 Download
          
          **SpecTrace.exe** - Self-contained executable (~70MB)
          - ✅ No dependencies required - works on any Windows 10+ system
          - ✅ Single file download and run
          - ✅ Includes all .NET runtime components
          
          ### ✨ Key Features
          - **Comprehensive Hardware Detection** - CPU, Memory, Graphics, Storage, Security, Network
          - **Modern Interface** - Clean UI with light/dark themes and intuitive navigation
          - **Multiple Export Formats** - JSON, XML, and text formats for different use cases
          - **Privacy Protection** - Built-in PII redaction keeps your data safe
          - **Portable Application** - No installation required, runs from anywhere
          - **Professional Ready** - Perfect for IT support, documentation, and diagnostics
          
          ### 🔧 System Requirements
          - Windows 10 (version 1903+) or Windows 11
          - 4 GB RAM minimum (8 GB recommended)
          - 10 MB free disk space
          - Standard user permissions (Administrator not required for basic scanning)
          
          ### 🚀 Quick Start
          1. Download `SpecTrace.exe`
          2. Run the executable (no installation needed)
          3. View comprehensive system information instantly
          4. Export data in your preferred format
          
          ### 📚 Documentation
          - **[📖 User Guide](https://github.com/${{ github.repository }}/blob/main/docs/USER_GUIDE.md)** - Complete usage instructions
          - **[❓ FAQ](https://github.com/${{ github.repository }}/blob/main/docs/FAQ.md)** - Common questions answered  
          - **[🛠️ Troubleshooting](https://github.com/${{ github.repository }}/blob/main/docs/TROUBLESHOOTING.md)** - Solve common issues
          
          ### 🔐 Security & Privacy
          - No data sent to external servers
          - All processing happens locally on your computer
          - Built-in privacy protection with PII redaction
          - Read-only operations - never modifies your system
          - Portable - leaves no traces when closed
          
          ---
          
          **Need help?** Check our [documentation](https://github.com/${{ github.repository }}/tree/main/docs) or [report an issue](https://github.com/${{ github.repository }}/issues).
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}