name: Release Build

on:
  push:
    tags:
      - 'v*'
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore src/SpecTrace/SpecTrace.csproj
      
    - name: Build Release
      run: dotnet build src/SpecTrace/SpecTrace.csproj --configuration Release --no-restore
      
    - name: Publish Framework-Dependent Executable
      run: |
        dotnet publish src/SpecTrace/SpecTrace.csproj `
          --configuration Release `
          --runtime win-x64 `
          --self-contained false `
          --output publish-framework `
          -p:PublishSingleFile=true
          
    - name: Publish Self-Contained Executable
      run: |
        dotnet publish src/SpecTrace/SpecTrace.csproj `
          --configuration Release `
          --runtime win-x64 `
          --self-contained true `
          --output publish-standalone `
          -p:PublishSingleFile=true
          
    - name: Verify Build Outputs
      run: |
        Write-Output "=== Framework-Dependent Build ==="
        Get-ChildItem -Path "publish-framework" -Recurse
        Write-Output "`n=== Self-Contained Build ==="
        Get-ChildItem -Path "publish-standalone" -Recurse
        
    - name: Upload Release Assets
      if: github.event_name == 'release' || startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          publish-framework/SpecTrace.exe
          publish-standalone/SpecTrace.exe
        body: |
          ## 🚀 SpecTrace Release
          
          Professional Windows system information tool for hardware analysis and diagnostics.
          
          ### 📥 Download Options
          
          **SpecTrace.exe** (Recommended)
          - Requires .NET 8.0 Runtime (usually already installed)
          - Smaller download (~10-15 MB)
          - Better performance
          
          **SpecTrace.exe** (Self-Contained - from publish-standalone folder)
          - No dependencies required
          - Larger download (~150 MB)
          - Works on any Windows 10+ system
          
          ### ✨ Features
          - Comprehensive hardware detection (CPU, Memory, Graphics, Storage, Security)
          - Modern UI with light/dark themes  
          - Export to JSON, XML, and text formats
          - Privacy-focused with PII redaction
          - Portable - no installation required
          
          ### 🔧 System Requirements
          - Windows 10 (version 1903+) or Windows 11
          - .NET 8.0 Runtime (for standard version)
          - 4 GB RAM minimum
          - Standard user permissions
          
          ### 🚀 Quick Start
          1. Download SpecTrace.exe
          2. Run the executable
          3. View comprehensive system information instantly
          
          📚 **Documentation:** [User Guide](https://github.com/${{ github.repository }}/blob/main/docs/USER_GUIDE.md) | [FAQ](https://github.com/${{ github.repository }}/blob/main/docs/FAQ.md) | [Troubleshooting](https://github.com/${{ github.repository }}/blob/main/docs/TROUBLESHOOTING.md)
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}